services:
  # Contenedor Único Todo-en-Uno: API REST (Java 21) + PostgreSQL
  fleethub_app:
    build:
      context: ./fleethub-api
      dockerfile: Dockerfile
    container_name: fleethub_all_in_one
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5432:5432"
    volumes:
      - fleethub_db_data:/var/lib/postgresql/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/fleethub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PORT: 8080

volumes:
  fleethub_db_data:
    driver: local
